# -*- coding: utf-8 -*-
"""sentiment app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K-WeTORanQP-6IP0wxIwxC-h3iGpcekC
"""

from flask import Flask, render_template, request
import joblib

app = Flask(__name__)

clf = joblib.load('sentiment_model_imdb.pkl')
vectorizer = joblib.load('tfidf_vectorizer_imdb.pkl')

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    if request.method == 'POST':
        text = request.form['text']
        # Vectorize text
        text_vectorized = vectorizer.transform([text])
        # Predict sentiment
        sentiment = clf.predict(text_vectorized)[0]
        return render_template('result.html', sentiment=sentiment)

if __name__ == '__main__':
    app.run(debug=True)